#!/bin/python
# -*- coding: utf-8 -*-

import numpy as np
import os
import math

def normal(vector):
	return math.sqrt(vector[0]**2+vector[1]**2+vector[2]**2)

def angle(vector1,vector2):
	v1len = normal(vector1)
	v2len = normal(vector2)
	v1_v2 = vector1[0]*vector2[0] + vector1[1]*vector2[1] + vector1[2]*vector2[2]
	cosang = v1_v2/(v1len*v2len)
	return math.acos(cosang)/math.pi*180


def raw2xyz(idir,odir,oname):
	rawfile = []
	for i in os.listdir(idir):
		tmp = os.path.join(idir,i)
		if os.path.isfile(tmp) and 'raw' in i:
			rawfile.append(tmp)

	for name in rawfile:
		if 'type' in name:
			da_type = np.loadtxt(name)
		elif 'box' in name:
			da_box = np.loadtxt(name)
		elif 'force' in name:
			da_force = np.loadtxt(name)
		elif 'coord' in name:
			da_coord = np.loadtxt(name)
		elif 'energy' in name:
			da_ene = np.loadtxt(name)
		elif 'virial' in name:
			da_viri = np.loadtxt(name)

	natoms = len(da_type)
	nframes = len(da_box)
	coords = da_coord.reshape(nframes,natoms,3)
	#print(coords.shape)	

	with open(os.path.join(odir,oname),'w') as f:
		for i in range(coords.shape[0]):
			f.write(str(natoms)+'\n')
			#f.write('Generated by Qiang \n')
			v1 = da_box[i][0:3]
			v2 = da_box[i][3:6]
			v3 = da_box[i][6:9]
			#f.write('{:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f}\n'.format(normal(v1),normal(v2),normal(v3),angle(v1,v2),angle(v2,v3),angle(v1,v3)))
			f.write('Lattice="{:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f}"\n'.format(\
										da_box[i][0],da_box[i][1],da_box[i][2],\
										da_box[i][3],da_box[i][4],da_box[i][5],\
										da_box[i][6],da_box[i][7],da_box[i][8]))
			for j in range(coords.shape[1]):
				f.write('{:3s} {:9.4f} {:9.4f} {:9.4f}\n'.format(str(da_type[j]),coords[i][j][0],coords[i][j][1],coords[i][j][2]))
			

def raw2pdb(idir,odir,oname):
	rawfile = []
	for i in os.listdir(idir):
		tmp = os.path.join(idir,i)
		if os.path.isfile(tmp) and 'raw' in i:
			rawfile.append(tmp)

	for name in rawfile:
		if 'type' in name:
			da_type = np.loadtxt(name)
		elif 'box' in name:
			da_box = np.loadtxt(name)
		elif 'force' in name:
			da_force = np.loadtxt(name)
		elif 'coord' in name:
			da_coord = np.loadtxt(name)
		elif 'energy' in name:
			da_ene = np.loadtxt(name)
		elif 'virial' in name:
			da_viri = np.loadtxt(name)

	natoms = len(da_type)
	nframes = len(da_box)
	coords = da_coord.reshape(nframes,natoms,3)
	#print(coords.shape)	

	with open(os.path.join(odir,oname),'w') as f:
		f.write('Generated by Qiang \n')
		for i in range(coords.shape[0]):
			#f.write(str(natoms)+'\n')
			f.write('MODEL {:>8d}\n'.format(i+1))
			v1 = da_box[i][0:3]
			v2 = da_box[i][3:6]
			v3 = da_box[i][6:9]
			f.write('CRYST1 {:>8.3f} {:>8.3f} {:>8.3f} {:>6.2f} {:>6.2f} {:>6.2f} P 1           1\n'\
								.format(normal(v1),normal(v2),normal(v3),\
										angle(v2,v3),angle(v1,v3),angle(v1,v2)))
			#f.write('{:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f}\n'.format(normal(v1),normal(v2),normal(v3),angle(v1,v2),angle(v2,v3),angle(v1,v3)))
#			f.write('Lattice="{:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f} {:8.5f}"\n'.format(\
#										da_box[i][0],da_box[i][1],da_box[i][2],\
#										da_box[i][3],da_box[i][4],da_box[i][5],\
#										da_box[i][6],da_box[i][7],da_box[i][8]))
			for j in range(coords.shape[1]):
				f.write('%-6s%5d%1s%-4s%1s%-3s%1s%1s%4d%4s%8.3f%8.3f%8.3f%8.4f%7.4f\n'\
						%('HETATM',int(j+1),'','X','','','','',0,'',\
									coords[i][j][0],coords[i][j][1],coords[i][j][2],\
									0.0,0.0))
			f.write('ENDMDL\n')
				#f.write('{:3s} {:9.4f} {:9.4f} {:9.4f}\n'.format(str(da_type[j]),coords[i][j][0],coords[i][j][1],coords[i][j][2]))
	#print(natoms,nframes)
	#print(rawfile)

if __name__ == '__main__':
	idir1 = '/Users/zhuqiang/Documents/My_Jobs@Nanjing/My_Competition/deepmd_hackathon/Cu_full/cu.bcc.02x02x02/02.md/sys-0016/deepmd'
	idir2 = '/Users/zhuqiang/Documents/My_Jobs@Nanjing/My_Competition/deepmd_hackathon/Cu_full/cu.fcc.02x02x02/02.md/sys-0032/deepmd'
	idir3 = '/Users/zhuqiang/Documents/My_Jobs@Nanjing/My_Competition/deepmd_hackathon/Cu_full/cu.hcp.02x02x02/02.md/sys-0016/deepmd'
	idir4 = '/Users/zhuqiang/Documents/My_Jobs@Nanjing/My_Competition/deepmd_hackathon/Cu_full/cu.bcc.02x02x02.high_pressure/02.md/sys-0016/deepmd'
	idir5 = '/Users/zhuqiang/Documents/My_Jobs@Nanjing/My_Competition/deepmd_hackathon/Cu_full/cu.fcc.02x02x02.high_pressure/02.md/sys-0032/deepmd'
	idir6 = '/Users/zhuqiang/Documents/My_Jobs@Nanjing/My_Competition/deepmd_hackathon/Cu_full/cu.hcp.02x02x02.high_pressure/02.md/sys-0016/deepmd'
	odir = '.'
	#oname1 = 'cu.bcc.02x02x02.xyz'
	#oname2 = 'cu.fcc.02x02x02.xyz'
	#oname3 = 'cu.hcp.02x02x02.xyz'
	#oname4 = 'cu.bcc.02x02x02.high_pressure.xyz'
	#oname5 = 'cu.fcc.02x02x02.high_pressure.xyz'
	#oname6 = 'cu.hcp.02x02x02.high_pressure.xyz'
	#raw2xyz(idir1,odir,oname1)
	#raw2xyz(idir2,odir,oname2)
	#raw2xyz(idir3,odir,oname3)
	#raw2xyz(idir4,odir,oname4)
	#raw2xyz(idir5,odir,oname5)
	#raw2xyz(idir6,odir,oname6)

	oname1p = 'cu.bcc.02x02x02.pdb'
	oname2p = 'cu.fcc.02x02x02.pdb'
	oname3p = 'cu.hcp.02x02x02.pdb'
	oname4p = 'cu.bcc.02x02x02.high_pressure.pdb'
	oname5p = 'cu.fcc.02x02x02.high_pressure.pdb'
	oname6p = 'cu.hcp.02x02x02.high_pressure.pdb'
	raw2pdb(idir1,odir,oname1p)
	raw2pdb(idir2,odir,oname2p)
	raw2pdb(idir3,odir,oname3p)
	raw2pdb(idir4,odir,oname4p)
	raw2pdb(idir5,odir,oname5p)
	raw2pdb(idir6,odir,oname6p)

